version: '3'
services:
  axonserver:
    image: axoniq/axonserver:latest
    ports:
    - 8024:8024
    - 8124:8124
  sse-baskets-mongodb:
    image: mongo:4.1.2
    command: mongod
    ports:
    - 27017:27017
  sse-baskets-api:
    #build: .
    image: sse-baskets-api:latest
    ports:
    - 8686:8686
    depends_on:
    - sse-baskets-mongodb
    - axonserver
    network_mode: "host"
