debug: true

#logging:
#  level:
#    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8686

spring:
  application:
    name: "@project.name@"
  resources:
    chain:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017


---
spring:
  profiles: docker

#  data:
#    mongodb:
#      host: sse-baskets-mongodb
#      port: 27017
  